### ISSUE TITLE
[BUG] Cannot rename an entity

### ISSUE THREAD

**Issue by benatspo** [typhon-project/typhonql#86]
Using the API, i'm not able to rename an existing entity.
The QL server returned an exception (see the logs hereafter).

Query: `rename NewEntity to NewEntity2`

ML model:
`<?xml version="1.0" encoding="ASCII"?>
<typhonml:Model xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:typhonml="http://org.typhon.dsls.typhonml.sirius">
  <entities name="Order">
    <attributes xsi:type="typhonml:Attribute" name="id">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
    <attributes xsi:type="typhonml:Attribute" name="productDate">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
    <attributes xsi:type="typhonml:Attribute" name="totalAmount">
      <type xsi:type="typhonml:IntType"/>
    </attributes>
    <relations name="users" type="//@entities.1" cardinality="one" opposite="//@entities.0/@relations.0"/>
  </entities>
  <entities name="User">
    <attributes xsi:type="typhonml:Attribute" name="id">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
    <attributes xsi:type="typhonml:Attribute" name="name">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
    <relations name="orders" type="//@entities.0" cardinality="zero_many"/>
  </entities>
  <entities name="NewEntity">
    <attributes xsi:type="typhonml:Attribute" name="id">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
    <attributes xsi:type="typhonml:Attribute" name="test">
      <type xsi:type="typhonml:StringType" maxSize="32"/>
    </attributes>
  </entities>
  <databases xsi:type="typhonml:RelationalDB" name="RelationalDatabase">
    <tables name="OrderDB" entity="//@entities.0">
      <indexSpec name="orderIndex" attributes="//@entities.0/@attributes.0"/>
      <idSpec attributes="//@entities.0/@attributes.0"/>
    </tables>
    <tables name="UserDB" entity="//@entities.1">
      <indexSpec name="userIndex" attributes="//@entities.1/@attributes.1"/>
      <idSpec attributes="//@entities.1/@attributes.1"/>
    </tables>
    <tables name="NewEntityDB" entity="//@entities.2"/>
  </databases>
  <databases xsi:type="typhonml:DocumentDB" name="DocumentDatabase"/>
</typhonml:Model>
`

API POST call: `http://localhost:8080/api/update` with body: rename NewEntity to NewEntity2

Output of `docker-compose logs qlserver:

02:24:08.946 [qtp2075809815-14] TRACE engineering.swat.typhonql.server.QLRestServer - Received arguments: {
command: rename NewEntity to NewEntity2
... <ML Model> ...
databaseInfo[DatabaseInfo [host=DocumentDatabase, port=27017, dbName=DocumentDatabase, dbms=MongoDb, user=username, password=password], DatabaseInfo [host=RelationalDatabase, port=3306, dbName=RelationalDatabase, dbms=MariaDB, user=root, password=password], DatabaseInfo [host=polystore-mongo, port=27017, dbName=polystore_db, dbms=MongoDb, user=admin, password=admin]]}
02:24:08.947 [qtp2075809815-14] TRACE engineering.swat.typhonql.server.QLRestServer - Running command: {
command: rename NewEntity to NewEntity2
... <ML Model> ...
databaseInfo[DatabaseInfo [host=DocumentDatabase, port=27017, dbName=DocumentDatabase, dbms=MongoDb, user=username, password=password], DatabaseInfo [host=RelationalDatabase, port=3306, dbName=RelationalDatabase, dbms=MariaDB, user=root, password=password], DatabaseInfo [host=polystore-mongo, port=27017, dbName=polystore_db, dbms=MongoDb, user=admin, password=admin]]}
        at lang::typhonql::RunUsingCompiler(|main://lang::typhonql::RunUsingCompiler||lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(9016,7,<221,45>,<221,52>): CallFailed(
  |lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(9016,7,<221,45>,<221,52>),
  ["NewEntity","NewEntity2"])
        at renameEntity(|lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(8980,46,<221,9>,<221,55>))
        at ddl2scriptAux(|lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(8722,50,<214,12>,<214,62>))
        at ddl2script(|lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(693,173,<28,0>,<32,1>))
        at request2script(|lib://typhonql/src/lang/typhonql/Request2Script.rsc|(2445,17,<86,13>,<86,30>))
        at runUpdate(|lib://typhonql/src/lang/typhonql/RunUsingCompiler.rsc|(1215,32,<44,11>,<44,43>))
        at runUpdate(|lib://typhonql/src/lang/typhonql/RunUsingCompiler.rsc|(3935,38,<125,9>,<125,47>))
02:24:09.235 [qtp2075809815-14] ERROR engineering.swat.typhonql.server.QLRestServer - Failed to handle response
org.rascalmpl.interpreter.control_exceptions.Throw: |lib://typhonql/src/lang/typhonql/DDL2Script.rsc|:221,45: CallFailed(
  |lib://typhonql/src/lang/typhonql/DDL2Script.rsc|(9016,7,<221,45>,<221,52>),
  ["NewEntity","NewEntity2"])
        at org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:138) ~[rascal-0.18.0.jar:?]
        at java.lang.Throwable.<init>(Throwable.java:266) ~[?:1.8.0_252]
        at java.lang.Exception.<init>(Exception.java:66) ~[?:1.8.0_252]
        at java.lang.RuntimeException.<init>(RuntimeException.java:62) ~[?:1.8.0_252]
        at org.rascalmpl.interpreter.control_exceptions.ControlException.<init>(ControlException.java:25) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:73) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:93) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.callFailed(RuntimeExceptionFactory.java:110) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:536) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:759) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$IfThen.interpret(Statement.java:604) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:416) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:394) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:533) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:759) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$IfThen.interpret(Statement.java:604) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.ConcretePatternDispatchedFunction.call(ConcretePatternDispatchedFunction.java:200) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.ConcretePatternDispatchedFunction.call(ConcretePatternDispatchedFunction.java:177) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:416) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:394) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:533) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Declarator$Default.interpret(Declarator.java:53) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.LocalVariableDeclaration$Default.interpret(LocalVariableDeclaration.java:36) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$VariableDeclaration.interpret(Statement.java:1005) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:533) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.utils.Cases$DefaultBlock.matchAndEval(Cases.java:252) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Switch.interpret(Statement.java:900) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:533) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:205) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:759) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$IfThenElse.interpret(Statement.java:679) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$NonEmptyBlock.interpret(Statement.java:759) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$IfThen.interpret(Statement.java:604) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:416) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:394) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:533) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:400) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:333) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:416) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:394) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:385) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:710) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:694) ~[rascal-0.18.0.jar:?]
        at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:683) ~[rascal-0.18.0.jar:?]
        at nl.cwi.swat.typhonql.client.XMIPolystoreConnection.lambda$4(XMIPolystoreConnection.java:208) ~[typhonql-0.1.0-SNAPSHOT.jar:?]
        at org.rascalmpl.util.ConcurrentSoftReferenceObjectPool.useAndReturn(ConcurrentSoftReferenceObjectPool.java:96) ~[rascal-0.18.0.jar:?]
        at nl.cwi.swat.typhonql.client.XMIPolystoreConnection.evaluateUpdate(XMIPolystoreConnection.java:203) ~[typhonql-0.1.0-SNAPSHOT.jar:?]
        at nl.cwi.swat.typhonql.client.XMIPolystoreConnection.executeUpdate(XMIPolystoreConnection.java:197) ~[typhonql-0.1.0-SNAPSHOT.jar:?]
        at engineering.swat.typhonql.server.QLRestServer.handleCommand(QLRestServer.java:209) ~[classes/:?]
        at engineering.swat.typhonql.server.QLRestServer.handle(QLRestServer.java:245) ~[classes/:?]
        at engineering.swat.typhonql.server.QLRestServer.access$300(QLRestServer.java:45) ~[classes/:?]
        at engineering.swat.typhonql.server.QLRestServer$1.doPost(QLRestServer.java:277) ~[classes/:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485) ~[jetty-servlet-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.Server.handle(Server.java:500) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270) [jetty-server-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.26.v20200117.jar:9.4.26.v20200117]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by tvdstorm** [comment]
Should be fixed in 6a56a82
